### ISSUE TITLE
$ACE_ROOT/tests should also be compiled on travis-ci

### ISSUE THREAD

**Issue by jwillemsen** [iguessthislldo/OpenDDS-Android#2]
The $ACE_ROOT/tests has a lot of compiler/features testing, as additional test this directory should also be compiled as part of the travis-ci testing

**Comment by iguessthislldo** [comment]
Sure, I just pushed a few commits and we'll see how that goes. I was hoping to getting to that when I was formally working on this, but I didn't have much time and just building OpenDDS was the priority.

I also put up the link to the travis in the readme.

**Comment by jwillemsen** [comment]
Maybe LD_LIBRARY_PATH has to be set correctly? You should use the same environment when compiling the tests as you do the OpenDDS core, isn't the configure script generating an environment script?

**Comment by iguessthislldo** [comment]
It appears that ACE_ROOT was wrong when I was running mpc in configure.sh, this has been fixed. The tests fail to build and fixes for that are in [ACE_TAO PR796](https://github.com/DOCGroup/ACE_TAO/pull/796).
